# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "emails", :force => true do |t|
    t.column "from",        :string
    t.column "to",          :string
    t.column "subject",     :string
    t.column "body",        :string
    t.column "attachments", :string
    t.column "bytes",       :integer
    t.column "spam",        :boolean
    t.column "spam_score",  :integer
    t.column "created_at",  :datetime
  end

  add_index "emails", ["created_at"], :name => "index_emails_on_created_at"
  add_index "emails", ["from"], :name => "index_emails_on_from"

  create_table "reports", :force => true do |t|
    t.column "body",       :text
    t.column "from",       :datetime
    t.column "to",         :datetime
    t.column "order",      :string
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "webs", :force => true do |t|
    t.column "dia",        :integer
    t.column "ip",         :string
    t.column "domain",     :string
    t.column "hora_inici", :string
    t.column "hora_fi",    :string
    t.column "bytes",      :integer
    t.column "contador",   :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "webs", ["dia"], :name => "index_webs_on_dia"
  add_index "webs", ["domain"], :name => "index_webs_on_domain"
  add_index "webs", ["ip"], :name => "index_webs_on_ip"

end
